### PR TITLE
Integration test with confluent docker images

### PR DESCRIPTION
**Pull request by compae**

### CODE REVIEW

**Comment by witokondoria** [comment]
the docker/zookeeper.out should be gitignored

**Comment by compae** [comment]
:shipit:

**Comment by stratiocommit** [comment]
A job will handle this PR ASAP on [Jenkins](http://jenkins.stratio.com/job/SparkLibs/job/SparkKafka/87/)

**Comment by stratiocommit** [comment]
Rebase && testing in progress

**Comment by witokondoria** [comment]
:shipit:

**Comment by stratiocommit** [comment]
A job will handle this PR ASAP on [Jenkins](http://jenkins.stratio.com/job/SparkLibs/job/SparkKafka/93/)

**Comment by stratiocommit** [comment]
Rebase && testing in progress

**Pull request merged**
