### PR TITLE
Sources generation

### PR DESCRIPTION
**Pull request by danielcsant**

### CODE REVIEW

**Comment by danielcsant** [comment]
:shipit:

**Comment by gbecares** [comment]
:shipit:

**Comment by stratiocommit** [comment]
A job will handle this PR ASAP on [Jenkins](http://jenkins.stratio.com/job/SparkLibs/job/SparkKafka/41/)

**Comment by stratiocommit** [comment]
Rebase && testing in progress

**Comment by gbecares** [comment]
:shipit:

**Comment by stratiocommit** [comment]
A job will handle this PR ASAP on [Jenkins](http://jenkins.stratio.com/job/SparkLibs/job/SparkKafka/44/)

**Comment by stratiocommit** [comment]
Rebase && testing in progress

**Pull request merged**
